#!/bin/bash

if [ $# -eq 0 ]; then
  while :
  do
      clear
      git --no-pager log --graph --pretty=oneline --abbrev-commit --decorate --all $*
      sleep 1
  done
fi

if [ $# -eq 1 ]; then
  while :
  do
      clear
      git --no-pager log -$1 --graph --pretty=oneline --abbrev-commit --decorate --all
      sleep 1
  done
fi
